export const GET_EMPLOYEES_RESPONSE = 'GET_EMPLOYEES_RESPONSE';
export const GET_EMPLOYEE_RESPONSE = 'GET_EMPLOYEE_RESPONSE';
export const ADD_NEW_EMPLOYEE_RESPONSE = 'ADD_NEW_EMPLOYEE_RESPONSE';
export const UPDATE_EXISTING_EMPLOYEE_RESPONSE = 'UPDATE_EXISTING_EMPLOYEE_RESPONSE';
export const DELETE_EMPLOYEE_RESPONSE = 'DELETE_EMPLOYEE_RESPONSE';

export const GET_AUTHORS_RESPONSE = 'GET_AUTHORS_RESPONSE';

export const API_CALL_BEGIN = 'API_CALL_BEGIN';
export const API_CALL_ERROR = 'API_CALL_ERROR';
